public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 2");
        var a = 4;
        dog = dog + a;
        cat = cat + a;
        paper = paper + a;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 3");
        var b = 3.5;
        var c = 1.6;
        var e = 7639;
        dog = dog - b;
        cat = cat - c;
        paper = paper - e;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("адача 4");
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        System.out.println("Задача 5");
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        System.out.println("Задача 6");
        var manOne = 78.2;
        var manTwo = 82.7;
        var result = manTwo + manOne;
        var resultTwo = manTwo - manOne;
        System.out.println("Общая масса двух бойцов равна " + result + " кг, а разница в весе между двумя бойцами равна " + resultTwo + " кг");
        System.out.println("Задача 7");
        var ost = manTwo % manOne;
        System.out.println("Остаток от деления между двумя весами равен " + ost);
        System.out.println("Задача 8.1");
        var h = 640;
        var rabotnik = h / 8;
        System.out.println("Всего работников в компании " + rabotnik + " человек");
        System.out.println("Задача 8.2");
        var vsegoR = rabotnik + 94;
        var vsegoH = h / vsegoR;
        System.out.println("Если в компании работает " + vsegoR + " человек, то весго " + vsegoH + " часов работы должно быть поделено между сотрудниками");
    }
}